# webapp/home/scopes.py
SCOPES = [
    "cos-spu",
    "ecotrends",
    "edi",
    # "icarus",
    "knb-lter-and",
    "knb-lter-arc",
    "knb-lter-bes",
    "knb-lter-ble",
    "knb-lter-bnz",
    "knb-lter-cap",
    "knb-lter-cce",
    "knb-lter-cdr",
    "knb-lter-cwt",
    "knb-lter-fce",
    "knb-lter-gce",
    "knb-lter-hbr",
    "knb-lter-hfr",
    "knb-lter-jrn",
    "knb-lter-kbs",
    "knb-lter-knz",
    "knb-lter-luq",
    "knb-lter-mcm",
    "knb-lter-mcr",
    "knb-lter-msp",
    "knb-lter-nes",
    "knb-lter-nga",
    "knb-lter-nin",
    "knb-lter-ntl",
    "knb-lter-nwk",
    "knb-lter-nwt",
    "knb-lter-pal",
    "knb-lter-pie",
    "knb-lter-sbc",
    "knb-lter-sev",
    "knb-lter-sgs",
    "knb-lter-vcr",
    "lter-landsat",
    "lter-landsat-ledaps",
    "msb-cap",
    "msb-paleon",
    "msb-tempbiodev",
]

SCOPE_CHOICES = [(s, s) for s in SCOPES]  # For forms that need to select a scope
